### DISCUSSION TITLE
when add actix-web crates ,project compile build so slowly?

### DISCUSSION THREAD

**Discussion by baoyachi** [actix/actix-web#1792] [General] [answered]
Is there a way to speed it up make build. Like use `features`,
```toml
[dependencies]
...
actix-web  = { version = "3.0.0", features = ["full"] }
```
