### DISCUSSION TITLE
Issue with hello world example from repo

### DISCUSSION THREAD

**Discussion by nav-mike** [actix/actix-web#3092] [Q&A] [answered]
Trying to use actix first time and basic example is not working for me:

Cargo.toml
```toml
[package]
name = "hello-world-actix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
```

main.rs
```rust
use actix_web::{get, web, App, HttpServer, Responder};

#[get("/hello/{name}")]
async fn greet(name: web::Path<String>) -> impl Responder {
    format!("Hello {name}!")
}

#[actix_web::main] // or #[tokio::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new().service(greet))
        .bind(("127.0.0.1", 8080))?
        .run()
        .await
}
```

when I try to use `cargo run`, I get 
```
Finished dev [unoptimized + debuginfo] target(s) in 0.62s
     Running `target/debug/hello-world-actix`
```

and it's not finishing. Tried rebuild using `cargo clean` and `cargo build` but did not help.
