### ISSUE TITLE
#[actix_rt::test] always returns InternalServerError

### ISSUE THREAD

**Issue by naomijub** [actix/actix-web#1357]
Until friday, Feb 14th 2020, My Actix tests were doing just fine. However now they are alwats returning HTTP 500. Currently they are integration tests in the folder `tests`. They work well with `cargo run`.

This is one test that fails:
```rust
#[actix_rt::test]
async fn signup_returns_created_status() {
      let mut app = test::init_service(
          App::new()
              .configure(app_routes)
      ).await;
    
      let signup_req = test::TestRequest::post()
          .uri("/auth/signup")
          .header("Content-Type", "application/json")
          .set_payload(read_json("signup.json").as_bytes().to_owned())
          .to_request();

      let resp = test::call_service(&mut app,signup_req).await;

      assert_eq!(resp.status(), StatusCode::CREATED);
}
```

## Expected Behavior

This assert was passing Friday and now it is not passing.

## Current Behavior
I tried checking out to master and it still failed. Also tried deleting `Cargo.lock` and `target`, and they kept failing. I replaced the `#[actix_rt::test]` to manually create actix runtime and it still failed.

## Possible Solution
Is there any other way to test this block without  `#[actix_rt::test]?

## Steps to Reproduce (for bugs)
1. This is repo https://github.com/web-dev-rust/todo-server
2. Execute it with `make test`

## Context
I am trying to develop a demo repo so my team can start using actix with our current stack in a daily basis. 

## Your Environment
I guess `make test` in the repo should be enough.  I am in the branch `postgres`

* Rust Version (I.e, output of `rustc -V`): 1.40
* Actix Web Version: 
```toml
[dependencies]
actix = "0.9.0"
actix-web = "2.0.0"
actix-rt = "1.0.0"
actix-http = "1.0.1"
fort = "0.3"
bastion = "0.3.4"
# ...

[dev-dependencies]
bytes = "0.5.3"
actix-service = "1.0.5"
```
