### ISSUE TITLE
Rwlock in state is easy to be poisoned

### ISSUE THREAD

**Issue by attila-lin** [actix/actix-web#1447]
## Expected Behavior
I use a struct like 
```rust
use tokio::sync::RwLock;
struct AppState {
    tables: Arc<RwLock<TableMap>>,
}

let app_state = web::Data::new(state);
```
and be put in `.app_data(app_state.clone())`

## Current Behavior
The Rwlock is easy to be poisoned and make the request be pending. 

## Possible Solution
Is it be caused by the single thread?

## Your Environment
my current config
```toml
actix = "0.10.0-alpha.2"
actix-web = "3.0.0-alpha.1"
actix-multipart = "0.2.0"
actix-files = { git = "https://github.com/actix/actix-web" }
actix-session = "0.4.0-alpha.1"
actix-cors = "0.3.0-alpha.1"
actix-rt = "1.0.0"
actix-web-actors = { git = "https://github.com/actix/actix-web" }
```

* Rust Version (I.e, output of `rustc -V`): rustc 1.43.0-nightly (54b7d21f5 2020-03-12)
* Actix Web Version:3.0.0-alpha.1
