### ISSUE TITLE
Would it be possible to get a actix-web-actors alpha release?

### ISSUE THREAD

**Issue by therealprof** [actix/actix-web#1477]
## Behavior

I'd like to test my application with the upcoming actix-web release but at the moment I can't because I need `actix-web-actors` and the latest released crate depends on the release versions of `actix-web` and others thereby creating fancy "you're using different versions of the traits" errors.

## Possible Solution

Bump the version of `actix-web-actors` to `3.0.0-alpha.1` and publish that.

**Comment by attila-lin** [comment]
I think you can just use the git version, like

```toml
actix = "0.10.0-alpha.2"
actix-web = {version="3.0.0-alpha.1", features=["rustls"]}
actix-multipart = { git = "https://github.com/actix/actix-web" }
actix-files = { git = "https://github.com/actix/actix-web" }
actix-session = "0.4.0-alpha.1"
actix-redis = { git="https://github.com/actix/actix-extras", features = ["web"] }
actix-service = {git="https://github.com/actix/actix-net"}
actix-http = "2.0.0-alpha.2"
actix-cors = "0.3.0-alpha.1"
actix-web-actors = { git = "https://github.com/actix/actix-web" }
actix-rt = "1.1.1"
```
