### ISSUE TITLE
Cannot use `tokio` runtime in `#[actix_web::main]` context

### ISSUE THREAD

**Issue by reza-ebrahimi** [actix/actix-web#2155]
**Problem:**

I get following panic error when I use `tokio` API and `await` on it using `#[actix_web::main]` runtime.

**Test Code:**

```rust
#[actix_web::main]
async fn main() -> std::io::Result<()> {
    let mut interval = tokio::time::interval(std::time::Duration::from_millis(10));
    interval.tick().await;

    Ok(())
}
```

**Error:**

```bash
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```

The following code works, But I need a workaround to use it regularly inside the current context.

```rust
use tokio::runtime::Runtime;

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    let rt = Runtime::new().unwrap();
    rt.block_on(async {
        let mut interval = tokio::time::interval(std::time::Duration::from_millis(10000));
        interval.tick().await;
        interval.tick().await;
    });

    Ok(())
}
```

**Comment by harscoet** [comment]
I guess you use the `version 3` of Actix (stable and default version) with Tokio `v1`, `v3` uses an old version of Tokio (`0.2`). You need to downgrade your Tokio version to `0.2` or upgrade Actix to `v4` (in beta)

https://github.com/actix/actix-web/releases/tag/web-v4.0.0-beta.1

```toml
[dependencies]
actix-web = "4.0.0-beta.5"
tokio = { version = "1.4.0", features = ["time"] }
```
or
```toml
[dependencies]
actix-web = "3"
tokio = { version = "0.2", features = ["time"] }
```

**Comment by reza-ebrahimi** [comment]
@harscoet  Thank you! It works.

```toml
[dependencies]
tokio = { version = "1.4.0", features = ["time"] }
actix-web = "4.0.0-beta.5"
```
