### ISSUE TITLE
Cannot compile a project using both actix-multipart and env_logger (Rust 1.53.0)

### ISSUE THREAD

**Issue by lerouxrgd** [actix/actix-web#2303]
## Expected Behavior

The program should compile (using stable Rust version `1.53.0`)

## Current Behavior

The program does not compile, when running `cargo build` I get:

```
error: linking with `cc` failed: exit status: 1

... lots of undefined references ...
``` 

## Steps to Reproduce (for bugs)

**Cargo.toml**

```toml
[package]
name = "actix-wont-compile"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-multipart = "0.3" # I also tried "0.4.0-beta.5"
actix-web = "3"         # I also tried "4.0.0-beta.8"
env_logger = "0.8"
```

**main.rs**

```rs
#[actix_web::main]
async fn main() -> std::io::Result<()> {
    std::env::set_var("RUST_LOG", "info");
    env_logger::init();
    Ok(())
}

```

Then `cargo build` doesn't work.

## Context

This prevents building servers for file upload that also use logging.

## Your Environment

* Rust Version:  `rustc 1.53.0 (53cb7b09b 2021-06-17)`
* Actix Web Version: `3` (and also the latest `4.0.0-beta.8`)
