### ISSUE TITLE
`Condition` middleware requires `Compat`

### ISSUE THREAD

**Issue by aliemjay** [actix/actix-web#2633]
`Condition` middleware is not generic enough over response body type, so it requires `Compat` wrapping the inner and outer middlewares

```rust
   --> src/bin/main.rs:116:13
    |
116 |       .wrap(Condition::new(env.as_str() == "production", HttpAuthentication::bearer(validator)))
    |        ---- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `BoxBody`, found enum `EitherBody`
    |        |
    |        required by a bound introduced by this call
    |
```

_Originally reported by @ppamorim in https://github.com/actix/actix-web/pull/2623#issuecomment-1031734444_

**Comment by robjtede** [comment]
More code context & versions needed. I don't think this would happen on latest pre-releases.

As always, minimal repro would be ideal.

**Comment by ppamorim** [comment]
@robjtede 

```toml
actix-web = "4.0.0-rc.2"
actix-cors = "0.6.0-beta.8"
actix-governor = "0.3.0-beta.1"
actix-web-httpauth = "0.6.0-beta.7"
```
