### ISSUE TITLE
actix-http cann't support http2

### ISSUE THREAD

**Issue by rootBiao** [actix/actix-web#2940]
https://github.com/actix/actix-web/blob/master/actix-http/examples/echo.rs
I run this example, but found the httpServer cann't handle the http2.
my rust version is 1.60.0

**my cargo.toml:**
```toml
[package]
name = "test_web"
version = "1.0.0"
edition = "2018"

[dependencies]
actix-http="3.2.2"
actix-server="2"
bytes = "1"
http = "0.2.5"
tracing = { version = "0.1.30"}
futures-util = { version = "0.3.7" }
actix-rt = { version = "2.2" }
env_logger = "0.9"
tokio = { version = "1.13.1" }
```

**test command:** curl  --verbose --http2-prior-knowledge http://127.0.0.1:8080

**the error logs**
![image](https://user-images.githubusercontent.com/87700793/205791151-96e24c8d-9e36-4085-9949-f880c3682c0c.png)
![image](https://user-images.githubusercontent.com/87700793/205791223-6c57d0e5-9b81-4c77-938b-c72bf8b39c86.png)
