### ISSUE TITLE
Segmentation fault (core dumped) with ssl + r2d2

### ISSUE THREAD

**Issue by damody** [actix/actix-web#565]
when use r2d2 with ssl, call any simple query with postgresql 10.5

use this config
```toml
diesel_codegen = { version = "0.16.1", features = ["postgres"] }
actix = "0.7.5"
actix-web = { version = "0.7.13", features = ["ssl"]}
openssl-sys = "0.9"
openssl = "0.10"
```
just merge example project ssl + diesel, then crash.
