### ISSUE TITLE
`Error sending data: disconnected` when server is behind `h2o` reverse proxy

### ISSUE THREAD

**Issue by alex35mil** [actix/actix-web#617]
When I place actix server behind [`h2o`](https://h2o.examp1e.net) reverse proxy I get this debug message after each request:

```
[2018-12-08T08:48:32Z DEBUG actix_web::server::h1] Error sending data: disconnected
```

All requests are handled fine: I don't see any issues in `h2o` logs or Chrome Network tab.

```
actix-web = "=0.7.15"
```

`h2o` config:

```yml
"app.dev:443":
  listen:
    port: 443
    ssl: !file ssl.conf
  paths:
    "/api":
      proxy.reverse.url: http://host.docker.internal:3100/api
```

App:

```rust
App::with_state(state)
  .resource("/api", |r| r.method(Method::POST).with_async(graphql::handler))
```
