### ISSUE TITLE
customized headers are awlays changed to lowercase

### ISSUE THREAD

**Issue by xujq1** [actix/actix-web#819]
I'm writing a app using actix web,but I met a problem,the customized headers are always changed to lowercase

here is my code snippet:
```rust

HttpResponse::Ok()
    .header("X-Pagination-Page", format!("{}", page)) 
    .header("X-Pagination-Page-Size", format!("{}", page_size))
    .header("X-Pagination-Total-Page", format!("{}", total_page.ceil()))
    .json(data_list)

```

my dependencies:
```toml

[dependencies]
actix-web = "1.0.0-alpha.4"
actix-session = "0.1.0-alpha.4"
actix-redis = { git = "https://github.com/actix/actix-redis.git", features = ["web"] }
actix-multipart = { git="https://github.com/actix/actix-web.git" }
actix-service = "0.3.6"

```

but the http client get a lowercase `x-pagination-page` header instead of `X-Pagination-Page`,

maybe it is a bug?
