### ISSUE TITLE
actix_web::middleware::logger::StreamLog not exposed

### ISSUE THREAD

**Issue by marcelbuesing** [actix/actix-web#853]
Hi,

I can not return an `App` instance that uses the `middleware::Logger::default()`.
I assume either logger module should be public, since StreamLog already is ir StreamLog explicitly exposed. 

```
error[E0603]: module `logger` is private

273 |     pub fn start() -> App<impl actix_service::NewService, actix_web::middleware::logger::StreamLog<actix_http::body::Body>> {
```

```Toml
[dependencies]
actix = "0.8.2"
actix-http= "0.2.0"
actix-web = "1.0.0-rc"
actix-web-actors = "1.0.0-beta.4"
actix-service = "0.4.0"
```

```Rust
pub fn start() -> App<impl actix_service::NewService, actix_web::middleware::logger::StreamLog<actix_http::body::Body>> {
        let app_state = AppState {};

        // bind to the server
        App::new()
            .data(app_state)
            .wrap(middleware::Logger::default())
            .service(web::resource("/").route(web::get().to(ws_index)))
    }
```
