### ISSUE TITLE
Invalid response with compression middleware enabled, but compression-related features disabled

### ISSUE THREAD

**Issue by roman-holovin** [actix/actix-web#997]
With `Cargo.toml` like this one

```toml
[dependencies]
actix-web = { version = "1.0", default-features = false, features = ["fail"] }
```
It is possible to use `actix-web::middleware::Compress`, but making requests with compression enabled will result in error like this one:
```
curl: (61) Error while processing content unencoding: incorrect header check
```
